// Mock data for demonstration
export const mockDecks = [
  {
    id: 1,
    name: 'Basic Conversations',
    language: 'Spanish',
    cardCount: 25,
    studiedToday: 10,
    progress: 40,
    lastStudied: '2 hours ago',
    difficulty: 'Beginner',
  },
  {
    id: 2,
    name: 'Business Vocabulary',
    language: 'Spanish',
    cardCount: 50,
    studiedToday: 0,
    progress: 20,
    lastStudied: '3 days ago',
    difficulty: 'Intermediate',
  },
  {
    id: 3,
    name: 'Common Phrases',
    language: 'French',
    cardCount: 30,
    studiedToday: 5,
    progress: 60,
    lastStudied: '1 hour ago',
    difficulty: 'Beginner',
  },
  {
    id: 4,
    name: 'Grammar Essentials',
    language: 'French',
    cardCount: 40,
    studiedToday: 0,
    progress: 10,
    lastStudied: '1 week ago',
    difficulty: 'Advanced',
  },
  {
    id: 5,
    name: 'Travel Vocabulary',
    language: 'German',
    cardCount: 35,
    studiedToday: 15,
    progress: 80,
    lastStudied: '30 minutes ago',
    difficulty: 'Beginner',
  },
];
